# Custom Language File for Launcher Customizer

[ejs.app]
title = "HeliosLauncher"

[ejs.landing]
mediaGitHubURL = "https://cagicac.fr"
mediaTwitterURL = "https://x.com/Cagicac1"
mediaInstagramURL = "https://www.instagram.com/Cagicac"
mediaYouTubeURL = "https://www.youtube.com/@Cagicac"
mediaDiscordURL = "https://discord.com/invite/5DthbUAajx"

[ejs.settings]
sourceGithubLink = "https://github.com/Cagicac/HeliosLauncher-NEWAPI"
supportLink = "https://github.com/Cagicac/HeliosLauncher-NEWAPI/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur WesterosCraft"
welcomeDescription = ""
welcomeDescCTA = ""
